security:
    enable_authenticator_manager: true

    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: /api
            provider: app_user_provider
            custom_authenticator:
                services:
                    - App\Security\ApiTokenAuthenticator

        main:
            anonymous: lazy
            provider: app_user_provider

            form_login:
                login_path: /login
                check_path: /login
                enable_csrf: true
                csrf_token_id: loginform

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800

            logout: ~

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/, roles: ROLE_USER }
